### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by noreiller** [cozy/cozy-indexer#3]
Hi, I installed cozy on my server (Ubuntu 14.04) but I can't start the data-system app.
I looked into the logs and I can see the following error: 

```
ReferenceError: levelup is not defined
    at getOptions (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/cozy-indexer/node_modules/search-index/node_modules/search-index-getter/docGetter.js:22:5)
```

The maintainer of the **search-index-getter** fixed this error in https://github.com/fergiemcdowall/search-index-getter/commit/8e101dec87fb356e1df98f5ed735fd3d903de09b but it's **not** updated in the [cozy-indexer/package.json](https://github.com/cozy/cozy-indexer/blob/master/package.json#L32)

If you need more details, tell me and I'll give you more information.
Thanks.

Update: **not** updated

**Comment by frankrousseau** [comment]
It may be due to a right problem in the `/usr/local/var/apps/cozy-data-system` folder.

**Comment by clochix** [comment]
Hi @noreiller,

Thanks for giving Cozy a try ☺

We sometime hit this problem on install or update of the data-system. Some dependencies fail to install.
You may try to reinstall them by hand:

```
cd /usr/local/cozy/apps/data-system
rm -rf node_modules/* && npm install --production -unsafe-perm true --user root
chown -R cozy-data-system: node_modules
cozy-monitor start data-system
```

If it fails, could you give us your versions of node and npm ?

**Comment by noreiller** [comment]
```
$ cozy-monitor start data-system
info - Starting data-system...
error - An error occured:
error - Start failed for data-system.
[Error: Error: connect ECONNREFUSED 127.0.0.1:9002]
```

node v4.4.3
npm v2.15.1

**Comment by noreiller** [comment]
I decided to remove and purge cozy and couchdb to reinstall it from scratch. Here is the log of `$ cozy_management show_reporting`: https://framabin.org/?1d37e1845d7dfa19#zCUrI/YDuwD7C09O9M6RKrjzpWq9Sr4oZeA1GJmC4j8=

**Comment by frankrousseau** [comment]
Hi @noreiller,

  Can you tell us more about your architecture?

**Comment by noreiller** [comment]
My server is a Kimsufi with Ubuntu 14.04.4 LTS (Linux 3.10.23-xxxx-std-ipv6-64 #1 SMP Mon Dec 9 18:53:52 CET 2013 x86_64 x86_64 x86_64 GNU/Linux)
I was using Cozy since a few months with Apache2 and a custom certificate (Let's Encrypt).
I switched to cozy_management when it came out.

To install cozy, I use [this guide](https://docs.cozy.io/en/host/install/install-on-ubuntu.html) except I install **cozy-apache2**.

**Comment by frankrousseau** [comment]
Thank you for additional information. @nledez could you have a look at that on monday?

**Comment by noreiller** [comment]
I fixed it yesterday thanks to @clochix. The owner of the folder /usr/local/var/cozy/data-system was not cozy-data-system and avoided the start of the data-sytem app.
